FROM apache/airflow:2.9.0

USER root
RUN apt-get update && apt-get install -y \
    libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 \
    libcups2 libdrm2 libdbus-1-3 libxkbcommon0 libxcomposite1 \
    libxdamage1 libxfixes3 libxrandr2 libgbm1 libasound2 \
    libpango-1.0-0 libcairo2 libxshmfence1 \
    && rm -rf /var/lib/apt/lists/*

USER airflow
RUN pip install playwright==1.44.0 aiomysql==0.2.0 python-dotenv==1.0.1 cryptography==42.0.5
RUN playwright install chromium